variables:
  NAME: 'ad-platform-dashboard'
  APP_VERSION:
    value: 'v0.0.1'
    description: 'Version of the application'
  BUILD_VARS: '--build-arg BUILD_TAG=$CI_PIPELINE_IID --build-arg NEXT_PUBLIC_SNOWPLOW_APP_ID=$NEXT_PUBLIC_SNOWPLOW_APP_ID --build-arg NEXT_PUBLIC_SNOWPLOW_NAME_TRACKER=$NEXT_PUBLIC_SNOWPLOW_NAME_TRACKER --build-arg NEXT_PUBLIC_APP_ENV=$PROJECT_ENV --build-arg NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL --build-arg NEXT_PUBLIC_APP_BASE_URL=$NEXT_PUBLIC_APP_BASE_URL --build-arg NEXT_PUBLIC_BASE_PATH=$NEXT_PUBLIC_BASE_PATH --build-arg NEXT_PUBLIC_IS_MANUAL_LOGIN=$NEXT_PUBLIC_IS_MANUAL_LOGIN --build-arg NEXT_PUBLIC_TRACKINGS_ENABLED=$NEXT_PUBLIC_TRACKINGS_ENABLED --build-arg NEXT_PUBLIC_SNOWPLOW_BASE_URL=$NEXT_PUBLIC_SNOWPLOW_BASE_URL --build-arg NEXT_PUBLIC_SNOWPLOW_COLLECTOR_URL=$NEXT_PUBLIC_SNOWPLOW_COLLECTOR_URL --build-arg IS_SENTRY_ENABLED=$IS_SENTRY_ENABLED --build-arg NEXT_PUBLIC_DATA_WEAVER_BASE_URL=$NEXT_PUBLIC_DATA_WEAVER_BASE_URL --build-arg NEXT_PUBLIC_DATA_WEAVER_API_KEY=$NEXT_PUBLIC_DATA_WEAVER_API_KEY'

include:
  - project: petco/RMN/devops/gitlab-runner-template
    ref: main
    file: build_deploy.yml
