export const transaction = [
  {
    createdDate: '2023-09-19',
    user: 'John Doe',
    team: 'Team A',
    ActionType: 'Login',
    spend: '$50',
    available: '$200',
  },
  {
    createdDate: '2023-09-18',
    user: 'Alice Smith',
    team: 'Team B',
    ActionType: 'Purchase',
    spend: '$100',
    available: '$150',
  },
  {
    createdDate: '2023-09-17',
    user: 'Bob Johnson',
    team: 'Team A',
    ActionType: 'Logout',
    spend: '$0',
    available: '$300',
  },
  {
    createdDate: '2023-09-16',
    user: 'Eva Davis',
    team: 'Team C',
    ActionType: 'Purchase',
    spend: '$75',
    available: '$225',
  },
  {
    createdDate: '2023-09-15',
    user: 'Mike Brown',
    team: 'Team B',
    ActionType: 'Login',
    spend: '$30',
    available: '$270',
  },
  {
    createdDate: '2023-09-14',
    user: 'Sarah Johnson',
    team: 'Team C',
    ActionType: 'Logout',
    spend: '$0',
    available: '$500',
  },
  {
    createdDate: '2023-09-13',
    user: 'David Smith',
    team: 'Team A',
    ActionType: 'Purchase',
    spend: '$150',
    available: '$350',
  },
  {
    createdDate: '2023-09-12',
    user: 'Linda Wilson',
    team: 'Team B',
    ActionType: 'Login',
    spend: '$40',
    available: '$260',
  },
  {
    createdDate: '2023-09-11',
    user: 'Chris Turner',
    team: 'Team C',
    ActionType: 'Logout',
    spend: '$0',
    available: '$600',
  },
  {
    createdDate: '2023-09-10',
    user: 'Emily Lee',
    team: 'Team A',
    ActionType: 'Purchase',
    spend: '$120',
    available: '$480',
  },
  {
    createdDate: '2023-09-09',
    user: 'Robert Davis',
    team: 'Team B',
    ActionType: 'Login',
    spend: '$60',
    available: '$360',
  },
  {
    createdDate: '2023-09-08',
    user: 'Megan Harris',
    team: 'Team C',
    ActionType: 'Logout',
    spend: '$0',
    available: '$700',
  },
  {
    createdDate: '2023-09-07',
    user: 'Daniel Johnson',
    team: 'Team A',
    ActionType: 'Purchase',
    spend: '$90',
    available: '$510',
  },
  {
    createdDate: '2023-09-06',
    user: 'Sophia Smith',
    team: 'Team B',
    ActionType: 'Login',
    spend: '$70',
    available: '$430',
  },
];

export const AddItemWallet = [
  {
    name: 'Project A',
    available: '$2000',
    status: 'Active',
    Priority: 'High',
    StartDate: '2023-09-01',
    endDate: '2023-09-30',
    budget: '$5000',
    spent: '$2500',
    Remaining: '$2500',
  },
  {
    name: 'Project B',
    available: '$1500',
    status: 'Inactive',
    Priority: 'Low',
    StartDate: '2023-08-15',
    endDate: '2023-09-15',
    budget: '$3000',
    spent: '$1000',
    Remaining: '$2000',
  },
  {
    name: 'Project C',
    available: '$3000',
    status: 'Active',
    Priority: 'Medium',
    StartDate: '2023-09-10',
    endDate: '2023-10-10',
    budget: '$6000',
    spent: '$3500',
    Remaining: '$2500',
  },
  {
    name: 'Project D',
    available: '$1000',
    status: 'Active',
    Priority: 'High',
    StartDate: '2023-09-05',
    endDate: '2023-09-25',
    budget: '$2000',
    spent: '$800',
    Remaining: '$1200',
  },
  {
    name: 'Project E',
    available: '$5000',
    status: 'Inactive',
    Priority: 'Low',
    StartDate: '2023-08-20',
    endDate: '2023-09-30',
    budget: '$7000',
    spent: '$4500',
    Remaining: '$2500',
  },
  // Add 15 more items as needed
];

export const WalletLinkedUser = [
  {
    name: 'Alice Johnson',
    Email: 'alice@example.com',
    userType: 'Premium',
    brand: 'Brand A',
    role: 'Admin',
  },
  {
    name: 'Bob Smith',
    Email: 'bob@example.com',
    userType: 'Free',
    brand: 'Brand B',
    role: 'User',
  },
  {
    name: 'Charlie Brown',
    Email: 'charlie@example.com',
    userType: 'Premium',
    brand: 'Brand C',
    role: 'User',
  },
  {
    name: 'David Wilson',
    Email: 'david@example.com',
    userType: 'Premium',
    brand: 'Brand A',
    role: 'Admin',
  },
  {
    name: 'Eva Davis',
    Email: 'eva@example.com',
    userType: 'Free',
    brand: 'Brand B',
    role: 'User',
  },
  {
    name: 'Frank White',
    Email: 'frank@example.com',
    userType: 'Premium',
    brand: 'Brand D',
    role: 'Admin',
  },
  {
    name: 'Grace Taylor',
    Email: 'grace@example.com',
    userType: 'Premium',
    brand: 'Brand C',
    role: 'User',
  },
  {
    name: 'Hannah Lee',
    Email: 'hannah@example.com',
    userType: 'Free',
    brand: 'Brand A',
    role: 'User',
  },
  {
    name: 'Ivy Miller',
    Email: 'ivy@example.com',
    userType: 'Premium',
    brand: 'Brand B',
    role: 'Admin',
  },
  {
    name: 'Jack Harris',
    Email: 'jack@example.com',
    userType: 'Premium',
    brand: 'Brand D',
    role: 'User',
  },
  {
    name: 'Katie Turner',
    Email: 'katie@example.com',
    userType: 'Free',
    brand: 'Brand C',
    role: 'User',
  },
  {
    name: 'Liam Thomas',
    Email: 'liam@example.com',
    userType: 'Premium',
    brand: 'Brand A',
    role: 'Admin',
  },
  {
    name: 'Mia Clark',
    Email: 'mia@example.com',
    userType: 'Premium',
    brand: 'Brand B',
    role: 'User',
  },
  {
    name: 'Noah Lewis',
    Email: 'noah@example.com',
    userType: 'Free',
    brand: 'Brand C',
    role: 'User',
  },
  {
    name: 'Olivia Moore',
    Email: 'olivia@example.com',
    userType: 'Premium',
    brand: 'Brand D',
    role: 'Admin',
  },
  {
    name: 'Penelope King',
    Email: 'penelope@example.com',
    userType: 'Premium',
    brand: 'Brand A',
    role: 'User',
  },
  {
    name: 'Quinn Adams',
    Email: 'quinn@example.com',
    userType: 'Free',
    brand: 'Brand B',
    role: 'User',
  },
  // Add more items as needed
];

export const LinkedTeam = [
  {
    name: 'Group A',
    groupid: '12345',
    createdBy: 'Alice Johnson',
    ofMember: 10,
    composition: 'Admins and Users',
  },
  {
    name: 'Group B',
    groupid: '67890',
    createdBy: 'Bob Smith',
    ofMember: 8,
    composition: 'Users',
  },
  {
    name: 'Group C',
    groupid: '54321',
    createdBy: 'Charlie Brown',
    ofMember: 15,
    composition: 'Admins and Users',
  },
  {
    name: 'Group D',
    groupid: '98765',
    createdBy: 'David Wilson',
    ofMember: 12,
    composition: 'Users',
  },
  {
    name: 'Group E',
    groupid: '24680',
    createdBy: 'Eva Davis',
    ofMember: 20,
    composition: 'Admins and Users',
  },
  {
    name: 'Group F',
    groupid: '13579',
    createdBy: 'Frank White',
    ofMember: 6,
    composition: 'Admins',
  },
  {
    name: 'Group G',
    groupid: '11223',
    createdBy: 'Grace Taylor',
    ofMember: 9,
    composition: 'Users',
  },
  {
    name: 'Group H',
    groupid: '33445',
    createdBy: 'Hannah Lee',
    ofMember: 14,
    composition: 'Admins and Users',
  },
  {
    name: 'Group I',
    groupid: '55667',
    createdBy: 'Ivy Miller',
    ofMember: 7,
    composition: 'Users',
  },
  {
    name: 'Group J',
    groupid: '77889',
    createdBy: 'Jack Harris',
    ofMember: 11,
    composition: 'Admins and Users',
  },
  {
    name: 'Group K',
    groupid: '99000',
    createdBy: 'Katie Turner',
    ofMember: 18,
    composition: 'Admins',
  },
  {
    name: 'Group L',
    groupid: '11221',
    createdBy: 'Liam Thomas',
    ofMember: 13,
    composition: 'Users',
  },
  {
    name: 'Group M',
    groupid: '33443',
    createdBy: 'Mia Clark',
    ofMember: 8,
    composition: 'Admins and Users',
  },
  {
    name: 'Group N',
    groupid: '55665',
    createdBy: 'Noah Lewis',
    ofMember: 16,
    composition: 'Users',
  },
  {
    name: 'Group O',
    groupid: '77887',
    createdBy: 'Olivia Moore',
    ofMember: 9,
    composition: 'Admins and Users',
  },
  {
    name: 'Group P',
    groupid: '99002',
    createdBy: 'Penelope King',
    ofMember: 12,
    composition: 'Users',
  },
  // Add more items as needed
];
